services:
  - type: web
    name: spin-win-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: MAIN_BOT_TOKEN
        sync: false
      - key: VIEW_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false